### ISSUE TITLE
Some words in strings are erroneously replaced

### ISSUE THREAD

**Issue by Lexikos** [mmikeww/AHK-v2-script-converter#115]
Input:
```
MsgBox % "Steve picked up his clipboard."
MsgBox Steve opened his clipboard.
```
Incorrect output:
```
MsgBox("Steve picked up his A_Clipboard.")
MsgBox("Steve opened his A_Clipboard.")
```
This is just a string, with no relation to the Clipboard variable. Regardless of case or the surrounding string, the insertion of `A_` is unwarranted.

This also applies to `A_LoopFileFullPath` and `A_LoopFileLongPath` (and maybe others?), although I suppose those are less likely to be an issue.

It appears that only the first occurrence of each name on a given line is replaced, which would be another bug if the replacement is warranted.

**Comment by andymbody** [comment]
> This is just a string, with no relation to the Clipboard variable. Regardless of case or the surrounding string, the insertion of `A_` is unwarranted.
> 
> This also applies to `A_LoopFileFullPath` and `A_LoopFileLongPath` (and maybe others?), although I suppose those are less likely to be an issue.

Have submitted a fix for keyword operations affecting strings. If the pull-request is accepted, many keywords will no longer be replaced within strings. The following should be corrected...
(A_LoopFileFullPath, A_LoopFileLongPath, ComSpec, Clipboard, ClipboardAll, ComObjParameter, A_isUnicode, A_BatchLines, A_NumBatchLines, New)
More may be corrected in future updates.

**Comment by andymbody** [comment]
> This is just a string, with no relation to the Clipboard variable. Regardless of case or the surrounding string, the insertion of `A_` is unwarranted.
> 
> This also applies to `A_LoopFileFullPath` and `A_LoopFileLongPath` (and maybe others?), although I suppose those are less likely to be an issue.

Have submitted a fix for keyword conversions affecting strings. If the pull-request is accepted, many keywords will no longer be replaced within strings. The following should be corrected...
(A_LoopFileFullPath, A_LoopFileLongPath, ComSpec, Clipboard, ClipboardAll, ComObjParameter, A_isUnicode, A_BatchLines, A_NumBatchLines, New)
More may be corrected in future updates.

**Comment by andymbody** [comment]
> This is just a string, with no relation to the Clipboard variable. Regardless of case or the surrounding string, the insertion of `A_` is unwarranted.
> 
> This also applies to `A_LoopFileFullPath` and `A_LoopFileLongPath` (and maybe others?), although I suppose those are less likely to be an issue.

Have submitted a fix for keyword conversions affecting strings. If the pull-request is accepted, many keywords will no longer be replaced within strings. The following should be corrected...
(A_BatchLines, A_isUnicode, A_LoopFileFullPath, A_LoopFileLongPath, A_NumBatchLines, Clipboard, ClipboardAll, ComObjParameter, ComSpec, New)
More may be corrected in future updates.

**Comment by Banaanae** [comment]
#156 will fix Lexikos' example, but user1823's example is still broken

Hopefully fully fixing shouldn't be too hard, as the base is here for these kinds of issues
